<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2014.2.1.284
*/

require_once('form_process.php');

$form = array(
	'subject' => '登入表單 送出',
	'heading' => '新的表單送出',
	'success_redirect' => '%e7%b8%bd%e8%a6%bd.html',
	'resources' => array(
		'checkbox_checked' => '已核取',
		'checkbox_unchecked' => '取消選取',
		'submitted_from' => '表單由此網站送出: %s',
		'submitted_by' => '訪客 IP 位址: %s',
		'too_many_submissions' => '此 IP 最近有太多送出記錄',
		'failed_to_send_email' => '傳送電子郵件失敗',
		'invalid_reCAPTCHA_private_key' => '無效的 reCAPTCHA 私密金鑰。',
		'invalid_field_type' => '不明的欄位類型「%s」。',
		'unknown_method' => '不明的伺服器要求方式'
	),
	'email' => array(
		'from' => 'bluepink1127@gmail.com',
		'to' => 'bluepink1127@gmail.com'
	),
	'fields' => array(
		'custom_U1280' => array(
			'type' => 'string',
			'label' => '帳號',
			'required' => false,
			'errors' => array(
			)
		),
		'Email' => array(
			'type' => 'email',
			'label' => '密碼',
			'required' => true,
			'errors' => array(
				'required' => '欄位「密碼」為必填。',
				'format' => '「密碼」欄位有無效的電子郵件。'
			)
		),
		'custom_U1296' => array(
			'type' => 'string',
			'label' => '郵箱',
			'required' => true,
			'errors' => array(
				'required' => '欄位「郵箱」為必填。'
			)
		),
		'custom_U1292' => array(
			'type' => 'string',
			'label' => '性別',
			'required' => true,
			'errors' => array(
				'required' => '欄位「性別」為必填。'
			)
		),
		'custom_U1300' => array(
			'type' => 'string',
			'label' => '鄉/鎮/區/市',
			'required' => true,
			'errors' => array(
				'required' => '欄位「鄉/鎮/區/市」為必填。'
			)
		),
		'custom_U1276' => array(
			'type' => 'string',
			'label' => '自我介紹',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
